
all: house_abst_w_d_cast.exe

run: all
	./house_abst_w_d_cast.exe

clean:
	rm -fr house_abst_w_d_cast.exe

house_abst_w_d_cast.exe: house_abst_w_d_cast.cpp
	g++ -std=c++17 -o house_abst_w_d_cast.exe house_abst_w_d_cast.cpp

