
all: single_house_maker.exe

run: all
	./single_house_maker.exe

clean:
	rm -fr single_house_maker.exe

single_house_maker.exe: single_house_maker.cpp
	g++ -o single_house_maker.exe single_house_maker.cpp

