
all: single_house_maker2.exe

run: all
	./single_house_maker2.exe

clean:
	rm -fr single_house_maker2.exe

single_house_maker2.exe: single_house_maker2.cpp
	g++ -o single_house_maker2.exe single_house_maker2.cpp

