
all: single_house_makerX.exe

run: all
	./single_house_makerX.exe

clean:
	rm -fr single_house_makerX.exe

single_house_makerX.exe: single_house_makerX.cpp
	g++ -o single_house_makerX.exe single_house_makerX.cpp

