
all: house_abst_w_vistor.exe

run: all
	house_abst_w_vistor.exe

clean:
	rm -fr house_abst_w_vistor.exe

house_abst_w_vistor.exe: house_abst_w_vistor.cpp
	g++ -o house_abst_w_vistor.exe house_abst_w_vistor.cpp

